#!/usr/bin/env sh
# This is taken from lukeSmith and modified to my needs
# This script will run mbsync and check
# for new email if there is an internet connection.
#
# If it detects new mail, it uses mpv to play a
# notification sound: notify.opus
#
# I have this run as a cronjob every 5 minutes.
#

export DISPLAY=:0.0

# Checks for internet connection and set notification script.
ping -q -c 1 1.1.1.1 > /dev/null || exit
# Settings are different for MacOS (Darwin) systems.
if [ "$(uname)" = "Darwin" ]
then
	notify() { osascript -e "display notification \"$2 in $1\" with title \"You've got Mail\" subtitle \"Account: $account\"" && sleep 2 ;}
else
	notify() { mpv --really-quiet ~/.scripts/notify.opus & pgrep -x dunst && "$2 new mail(s) in \`$1\` account." ;}
fi

echo " 🔃" > /tmp/mbsyncicon
pkill -RTMIN+12 i3blocks

# Run mbsync. You can feed this script different settings.
mbsync --all 
rm -f /tmp/mbsyncicon
pkill -RTMIN+12 i3blocks

# Check all accounts/mailboxes for new mail. Notify if there is new content.
for account in $(ls ~/mail)
do
	#List unread messages newer than last mailsync and count them
	newcount=$(find ~/mail/"$account"/Inbox/new/ -type f -newer ~/.config/.mailsynclastrun 2> /dev/null | wc -l)
	if [ "$newcount" -gt "0" ]
	then
		notify "$account" "$newcount" &
	fi
done

#Create a touch file that indicates the time of the last run of mailsync
touch ~/.config/.mailsynclastrun

