################
### MONITORS ###
################
#


# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,2880x1800@120,auto,1.6
monitor=HDMI-A-1,1920x1080,auto,1
monitor =desc:AOC Q3279WG5B 0x000074FC ,2560x1440,auto-left,1 

