# ============================================================================
# FZF — config only
# Shell integration (eval "$(fzf --zsh)") is in plugins.zsh so that
# atuin can overwrite Ctrl-R after fzf registers it.
# ============================================================================

# --- Colors + multi-select (generated by theme/justfile, see theme/fzf.tera) ---
source "$ZDOTDIR/conf/fzf-theme.zsh"

# --- Previews ---
# Reusable preview: eza tree for dirs, bat for files
show_file_or_dir_preview="if [ -d {} ]; then eza --tree --color=always {} | head -200; else bat -n --color=always --line-range :500 {}; fi"

export FZF_CTRL_T_OPTS="--preview '$show_file_or_dir_preview'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# --- Context-aware completion previews ---
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
    export|unset) fzf --preview "eval 'echo \${}'"                         "$@" ;;
    ssh)          fzf --preview 'dig {}'                                    "$@" ;;
    *)            fzf --preview "$show_file_or_dir_preview"                 "$@" ;;
  esac
}
