#!/bin/sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.

case $BLOCK_BUTTON in
  1) "$TERMINAL" -e "emacsclient -nce \"(mu4e)\"" ;;
	2) setsid $HOME/.scripts/tools/mailsync >/dev/null & ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>📬 Mail module:</b>
- Shows unread mail
- Shows 🔃 if syncing mail
- Left click opens mu4e
- Middle click syncs mail" ;;
esac

echo "$(du -a ~/mail/Inbox/new/ 2>/dev/null | sed -n '$=')$(cat /tmp/mbsyncicon 2>/dev/null)"
