[mailbox]
source          = imaps://ashfaq.farooqui@mailbox.org@imap.mailbox.org:993
source-cred-cmd = secret-tool lookup service mailbox.org username ashfaq.farooqui@mailbox.org
outgoing        = smtps+plain://ashfaq.farooqui@mailbox.org@smtp.mailbox.org:465
outgoing-cred-cmd = secret-tool lookup service mailbox.org username ashfaq.farooqui@mailbox.org
default         = INBOX
from            = Ashfaq Farooqui <ashfaq@ashfaqfarooqui.me>
copy-to         = Sent
