return {
  {
    "catppuccin",
    opts = {
      transparent_background = true,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      -- generated by theme/justfile into nvim/.config/nvim/colors/theme_generated.lua
      -- and kept in sync with every other app by `just -f theme/justfile apply <name>`
      colorscheme = "theme_generated",
    },
  },
}
